// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TCPPROTOCOL_H_
#define FLATBUFFERS_GENERATED_TCPPROTOCOL_H_

#include "flatbuffers/flatbuffers.h"

struct Vec3;

struct Message;
struct MessageBuilder;

struct S2C_TEST;
struct S2C_TESTBuilder;

struct C2S_TEST;
struct C2S_TESTBuilder;

enum MESSAGE_ID : uint8_t {
  MESSAGE_ID_NONE = 0,
  MESSAGE_ID_S2C_TEST = 1,
  MESSAGE_ID_C2S_TEST = 2,
  MESSAGE_ID_MIN = MESSAGE_ID_NONE,
  MESSAGE_ID_MAX = MESSAGE_ID_C2S_TEST
};

inline const MESSAGE_ID (&EnumValuesMESSAGE_ID())[3] {
  static const MESSAGE_ID values[] = {
    MESSAGE_ID_NONE,
    MESSAGE_ID_S2C_TEST,
    MESSAGE_ID_C2S_TEST
  };
  return values;
}

inline const char * const *EnumNamesMESSAGE_ID() {
  static const char * const names[4] = {
    "NONE",
    "S2C_TEST",
    "C2S_TEST",
    nullptr
  };
  return names;
}

inline const char *EnumNameMESSAGE_ID(MESSAGE_ID e) {
  if (flatbuffers::IsOutRange(e, MESSAGE_ID_NONE, MESSAGE_ID_C2S_TEST)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMESSAGE_ID()[index];
}

template<typename T> struct MESSAGE_IDTraits {
  static const MESSAGE_ID enum_value = MESSAGE_ID_NONE;
};

template<> struct MESSAGE_IDTraits<S2C_TEST> {
  static const MESSAGE_ID enum_value = MESSAGE_ID_S2C_TEST;
};

template<> struct MESSAGE_IDTraits<C2S_TEST> {
  static const MESSAGE_ID enum_value = MESSAGE_ID_C2S_TEST;
};

bool VerifyMESSAGE_ID(flatbuffers::Verifier &verifier, const void *obj, MESSAGE_ID type);
bool VerifyMESSAGE_IDVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vec3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vec3(float _x, float _y, float _z)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3, 12);

struct Message FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef MessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PACKET_TYPE = 4,
    VT_PACKET = 6
  };
  MESSAGE_ID packet_type() const {
    return static_cast<MESSAGE_ID>(GetField<uint8_t>(VT_PACKET_TYPE, 0));
  }
  const void *packet() const {
    return GetPointer<const void *>(VT_PACKET);
  }
  template<typename T> const T *packet_as() const;
  const S2C_TEST *packet_as_S2C_TEST() const {
    return packet_type() == MESSAGE_ID_S2C_TEST ? static_cast<const S2C_TEST *>(packet()) : nullptr;
  }
  const C2S_TEST *packet_as_C2S_TEST() const {
    return packet_type() == MESSAGE_ID_C2S_TEST ? static_cast<const C2S_TEST *>(packet()) : nullptr;
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_PACKET_TYPE) &&
           VerifyOffset(verifier, VT_PACKET) &&
           VerifyMESSAGE_ID(verifier, packet(), packet_type()) &&
           verifier.EndTable();
  }
};

template<> inline const S2C_TEST *Message::packet_as<S2C_TEST>() const {
  return packet_as_S2C_TEST();
}

template<> inline const C2S_TEST *Message::packet_as<C2S_TEST>() const {
  return packet_as_C2S_TEST();
}

struct MessageBuilder {
  typedef Message Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_packet_type(MESSAGE_ID packet_type) {
    fbb_.AddElement<uint8_t>(Message::VT_PACKET_TYPE, static_cast<uint8_t>(packet_type), 0);
  }
  void add_packet(flatbuffers::Offset<void> packet) {
    fbb_.AddOffset(Message::VT_PACKET, packet);
  }
  explicit MessageBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Message> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Message>(end);
    return o;
  }
};

inline flatbuffers::Offset<Message> CreateMessage(
    flatbuffers::FlatBufferBuilder &_fbb,
    MESSAGE_ID packet_type = MESSAGE_ID_NONE,
    flatbuffers::Offset<void> packet = 0) {
  MessageBuilder builder_(_fbb);
  builder_.add_packet(packet);
  builder_.add_packet_type(packet_type);
  return builder_.Finish();
}

struct S2C_TEST FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef S2C_TESTBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TEST = 4
  };
  const flatbuffers::String *test() const {
    return GetPointer<const flatbuffers::String *>(VT_TEST);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_TEST) &&
           verifier.VerifyString(test()) &&
           verifier.EndTable();
  }
};

struct S2C_TESTBuilder {
  typedef S2C_TEST Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_test(flatbuffers::Offset<flatbuffers::String> test) {
    fbb_.AddOffset(S2C_TEST::VT_TEST, test);
  }
  explicit S2C_TESTBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<S2C_TEST> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<S2C_TEST>(end);
    return o;
  }
};

inline flatbuffers::Offset<S2C_TEST> CreateS2C_TEST(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> test = 0) {
  S2C_TESTBuilder builder_(_fbb);
  builder_.add_test(test);
  return builder_.Finish();
}

inline flatbuffers::Offset<S2C_TEST> CreateS2C_TESTDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *test = nullptr) {
  auto test__ = test ? _fbb.CreateString(test) : 0;
  return CreateS2C_TEST(
      _fbb,
      test__);
}

struct C2S_TEST FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef C2S_TESTBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TEST = 4
  };
  int32_t test() const {
    return GetField<int32_t>(VT_TEST, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_TEST) &&
           verifier.EndTable();
  }
};

struct C2S_TESTBuilder {
  typedef C2S_TEST Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_test(int32_t test) {
    fbb_.AddElement<int32_t>(C2S_TEST::VT_TEST, test, 0);
  }
  explicit C2S_TESTBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<C2S_TEST> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<C2S_TEST>(end);
    return o;
  }
};

inline flatbuffers::Offset<C2S_TEST> CreateC2S_TEST(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t test = 0) {
  C2S_TESTBuilder builder_(_fbb);
  builder_.add_test(test);
  return builder_.Finish();
}

inline bool VerifyMESSAGE_ID(flatbuffers::Verifier &verifier, const void *obj, MESSAGE_ID type) {
  switch (type) {
    case MESSAGE_ID_NONE: {
      return true;
    }
    case MESSAGE_ID_S2C_TEST: {
      auto ptr = reinterpret_cast<const S2C_TEST *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MESSAGE_ID_C2S_TEST: {
      auto ptr = reinterpret_cast<const C2S_TEST *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyMESSAGE_IDVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyMESSAGE_ID(
        verifier,  values->Get(i), types->GetEnum<MESSAGE_ID>(i))) {
      return false;
    }
  }
  return true;
}

#endif  // FLATBUFFERS_GENERATED_TCPPROTOCOL_H_
