// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace TcpProtocol.Define
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct C2S_TEST : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static C2S_TEST GetRootAsC2S_TEST(ByteBuffer _bb) { return GetRootAsC2S_TEST(_bb, new C2S_TEST()); }
  public static C2S_TEST GetRootAsC2S_TEST(ByteBuffer _bb, C2S_TEST obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public C2S_TEST __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Test { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<TcpProtocol.Define.C2S_TEST> CreateC2S_TEST(FlatBufferBuilder builder,
      int test = 0) {
    builder.StartTable(1);
    C2S_TEST.AddTest(builder, test);
    return C2S_TEST.EndC2S_TEST(builder);
  }

  public static void StartC2S_TEST(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddTest(FlatBufferBuilder builder, int test) { builder.AddInt(0, test, 0); }
  public static Offset<TcpProtocol.Define.C2S_TEST> EndC2S_TEST(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<TcpProtocol.Define.C2S_TEST>(o);
  }
};


}
