// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace TcpProtocol.Define
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct C2S_HANDOUT_CARD : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static C2S_HANDOUT_CARD GetRootAsC2S_HANDOUT_CARD(ByteBuffer _bb) { return GetRootAsC2S_HANDOUT_CARD(_bb, new C2S_HANDOUT_CARD()); }
  public static C2S_HANDOUT_CARD GetRootAsC2S_HANDOUT_CARD(ByteBuffer _bb, C2S_HANDOUT_CARD obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public C2S_HANDOUT_CARD __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Num { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<TcpProtocol.Define.C2S_HANDOUT_CARD> CreateC2S_HANDOUT_CARD(FlatBufferBuilder builder,
      int num = 0) {
    builder.StartTable(1);
    C2S_HANDOUT_CARD.AddNum(builder, num);
    return C2S_HANDOUT_CARD.EndC2S_HANDOUT_CARD(builder);
  }

  public static void StartC2S_HANDOUT_CARD(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddNum(FlatBufferBuilder builder, int num) { builder.AddInt(0, num, 0); }
  public static Offset<TcpProtocol.Define.C2S_HANDOUT_CARD> EndC2S_HANDOUT_CARD(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<TcpProtocol.Define.C2S_HANDOUT_CARD>(o);
  }
};


}
