// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace TcpProtocol.Define
{

public enum MESSAGE_ID : byte
{
  NONE = 0,
  S2C_TEST = 1,
  C2S_TEST = 2,
  C2S_START_GAME = 3,
  S2C_START_GAME = 4,
  C2S_HANDOUT_CARD = 5,
  C2S_RING_BELL = 6,
  S2C_HANDOUT_CARD = 7,
  S2C_RING_BELL = 8,
  S2C_SOMEONE_DIE = 9,
  S2C_WIN = 10,
  S2C_FAIL = 11,
};


}
