// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace TcpProtocol.Define
{

public enum MESSAGE_ID : byte
{
  NONE = 0,
  S2C_TEST = 1,
  C2S_TEST = 2,
};


}
