// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace TcpProtocol.Define
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct S2C_TEST : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static S2C_TEST GetRootAsS2C_TEST(ByteBuffer _bb) { return GetRootAsS2C_TEST(_bb, new S2C_TEST()); }
  public static S2C_TEST GetRootAsS2C_TEST(ByteBuffer _bb, S2C_TEST obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public S2C_TEST __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Test { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTestBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetTestBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetTestArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<TcpProtocol.Define.S2C_TEST> CreateS2C_TEST(FlatBufferBuilder builder,
      StringOffset testOffset = default(StringOffset)) {
    builder.StartTable(1);
    S2C_TEST.AddTest(builder, testOffset);
    return S2C_TEST.EndS2C_TEST(builder);
  }

  public static void StartS2C_TEST(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddTest(FlatBufferBuilder builder, StringOffset testOffset) { builder.AddOffset(0, testOffset.Value, 0); }
  public static Offset<TcpProtocol.Define.S2C_TEST> EndS2C_TEST(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<TcpProtocol.Define.S2C_TEST>(o);
  }
};


}
