// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace TcpProtocol.Define
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct S2C_FAIL : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static S2C_FAIL GetRootAsS2C_FAIL(ByteBuffer _bb) { return GetRootAsS2C_FAIL(_bb, new S2C_FAIL()); }
  public static S2C_FAIL GetRootAsS2C_FAIL(ByteBuffer _bb, S2C_FAIL obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public S2C_FAIL __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Playernum { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<TcpProtocol.Define.S2C_FAIL> CreateS2C_FAIL(FlatBufferBuilder builder,
      int playernum = 0) {
    builder.StartTable(1);
    S2C_FAIL.AddPlayernum(builder, playernum);
    return S2C_FAIL.EndS2C_FAIL(builder);
  }

  public static void StartS2C_FAIL(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddPlayernum(FlatBufferBuilder builder, int playernum) { builder.AddInt(0, playernum, 0); }
  public static Offset<TcpProtocol.Define.S2C_FAIL> EndS2C_FAIL(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<TcpProtocol.Define.S2C_FAIL>(o);
  }
};


}
