// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace TcpProtocol.Define
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct S2C_HANDOUT_CARD : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static S2C_HANDOUT_CARD GetRootAsS2C_HANDOUT_CARD(ByteBuffer _bb) { return GetRootAsS2C_HANDOUT_CARD(_bb, new S2C_HANDOUT_CARD()); }
  public static S2C_HANDOUT_CARD GetRootAsS2C_HANDOUT_CARD(ByteBuffer _bb, S2C_HANDOUT_CARD obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public S2C_HANDOUT_CARD __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Num { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public TcpProtocol.Define.CARD? Card { get { int o = __p.__offset(6); return o != 0 ? (TcpProtocol.Define.CARD?)(new TcpProtocol.Define.CARD()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<TcpProtocol.Define.S2C_HANDOUT_CARD> CreateS2C_HANDOUT_CARD(FlatBufferBuilder builder,
      int num = 0,
      Offset<TcpProtocol.Define.CARD> cardOffset = default(Offset<TcpProtocol.Define.CARD>)) {
    builder.StartTable(2);
    S2C_HANDOUT_CARD.AddCard(builder, cardOffset);
    S2C_HANDOUT_CARD.AddNum(builder, num);
    return S2C_HANDOUT_CARD.EndS2C_HANDOUT_CARD(builder);
  }

  public static void StartS2C_HANDOUT_CARD(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddNum(FlatBufferBuilder builder, int num) { builder.AddInt(0, num, 0); }
  public static void AddCard(FlatBufferBuilder builder, Offset<TcpProtocol.Define.CARD> cardOffset) { builder.AddOffset(1, cardOffset.Value, 0); }
  public static Offset<TcpProtocol.Define.S2C_HANDOUT_CARD> EndS2C_HANDOUT_CARD(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<TcpProtocol.Define.S2C_HANDOUT_CARD>(o);
  }
};


}
